### PR TITLE
introducing rank

### PR DESCRIPTION
**Pull request by jamesgorrie**
Introducing rank - we will start peeling of pieces to get it into the general stack arrangement.

### CODE REVIEW

**Review by kenoir — APPROVED** [review]
👍 if you don't care about keeping the git history

**Comment by jamesgorrie** [comment]
It's quite fresh and we have it over in https://github.com/wellcomecollection/rank

**Comment by kenoir** [comment]
@jamesgorrie can you archive (with a deprecation message pointing here) or delete  https://github.com/wellcomecollection/rank?

**Comment by jamesgorrie** [comment]
Yup, was on the list ♻️

**Pull request merged**
